name: 1st World Problems
favicon: null
layout_spectrum: 0.879692156566307
typography_spectrum: 0.6379565561655909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5917287946213037
  lightness: 0.6880630573723465
  saturation: 0.8901507807895541
  rhythmicContrast: 0.6600955629255623
purpose: []
